### ISSUE TITLE
Sound doesn't play on iPad

### ISSUE THREAD

**Issue by wdhdev** [s3mant/vexatious-site#2]
The audio doesn't play on my iPad.

Model: iPad Air (2021)

**Comment by s3mant** [comment]
have you tried tapping once on the screen
it doesn't play on some devices due to overload of videos and audios at once.

**Comment by wdhdev** [comment]
> have you tried tapping once on the screen
> it doesn't play on some devices due to overload of videos and audios at once.

Will try.

**Comment by wdhdev** [comment]
Nope, still doesn't work.

**Comment by s3mant** [comment]
> Nope, still doesn't work.

did you try with the latest update??

**Comment by wdhdev** [comment]
> > Nope, still doesn't work.
> 
> did you try with the latest update??

I'll try later.

**Comment by wdhdev** [comment]
Works now.

**Comment by s3mant** [comment]
> Works now.

yeah it was cuz of overload
I reduced video size to 50 from 200
